### ISSUE TITLE
Guidance is required to run the code.

### ISSUE THREAD

**Issue by hinarashed** [sergeyk/anytime_recognition#1]
Error when running the project_281b.py is as below
{
Traceback (most recent call last):
  File "D:\anytime_recognition-master\project_281b.py", line 24, in <module>
    import tc
  File "D:\anytime_recognition-master\tc__init__.py", line 4, in <module>
    import gg
ImportError: No module named 'gg'
}
the Above error message was appeared when i run the code.As the code contains the "gg" module .
when i run running the "tc" module file name **init**.py the following warnings and errors appeared

Warning (from warnings module):
  File "D:\anytime_recognition-master\tc\mpltools\style__init__.py", line 42
    """, FutureWarning)
FutureWarning: 

```
The style-sheet functionality in mpltools has been integrated into
Matplotlib >= 1.4. This module will be removed in a future release.

Note that style-sheets used by `matplotlib.style` use the standard
Matplotlib rc-file syntax instead of the INI format used by `mpltools`.
This mostly means un-quoting strings and changing '=' to ':'.
```

Warning (from warnings module):
  File "C:\Python34\lib\site-packages\matplotlib__init__.py", line 876
    warnings.warn(self.msg_depr % (key, alt_key))
UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
Traceback (most recent call last):
  File "D:\anytime_recognition-master\tc__init__.py", line 11, in <module>
    import classifier
  File "D:\anytime_recognition-master\tc\classifier.py", line 1, in <module>
    import tc
ImportError: No module named 'tc'

 kindly help me to resolve these issues in code of anytime_recognition of code.

**Comment by hinarashed** [comment]
@sergeyk, @taras-sereda, @taosiqin1991,@ashkan-mokarian, @mrecachinas   .... Please, kindly help me to resolve the above issues in code files of "Anytime recognition of objects and Scenes"... as  i m unable to run the code.
