### ISSUE TITLE
TypeError: Empty 'DataFrame': no numeric data to plot

### ISSUE THREAD

**Issue by nabeelahmed** [sergeyk/anytime_recognition#2]
I have started exploring your work - for this I have [forked](https://github.com/nabeelahmed/anytime_recognition) it, installed it and commit-ed the missing packages in requirements and an improved README.

After all this, on my first run, the program kept running for while with lot of stdout, and ended up with a TypeError exception:
```
Traceback (most recent call last):
  File "project_281b.py", line 731, in <module>
    plot_results(dataset_name, policy_name, num_blocks)
  File "project_281b.py", line 641, in plot_results
    err_df.filter(regex='mean, retrained:|gaussian, retrained:|kNN \(euclidean\):|kNN \(dot\):|mcf').plot(marker='s', ax=ax)
  File "/home/nahmed/virtualenvs/venv_anytime_recognition/lib/python2.7/site-packages/pandas/tools/plotting.py", line 3773, in __call__
    sort_columns=sort_columns, **kwds)
  File "/home/nahmed/virtualenvs/venv_anytime_recognition/lib/python2.7/site-packages/pandas/tools/plotting.py", line 2642, in plot_frame
    **kwds)
  File "/home/nahmed/virtualenvs/venv_anytime_recognition/lib/python2.7/site-packages/pandas/tools/plotting.py", line 2469, in _plot
    plot_obj.generate()
  File "/home/nahmed/virtualenvs/venv_anytime_recognition/lib/python2.7/site-packages/pandas/tools/plotting.py", line 1041, in generate
    self._compute_plot_data()
  File "/home/nahmed/virtualenvs/venv_anytime_recognition/lib/python2.7/site-packages/pandas/tools/plotting.py", line 1150, in _compute_plot_data
    'plot'.format(numeric_data.__class__.__name__))
TypeError: Empty 'DataFrame': no numeric data to plot
```

I'd also like to add the exception (probably the handled ones) I got few times, while the program kept running

 > AttributeError: 'module' object has no attribute 'argpartsort'

A bog chunk of stdout with normal output and the exception:
```
Trained clf with 0.469 zeros in 2.309 s
Best params: {'C': 10}
Trained clf with 0.469 zeros in 2.250 s
Best params: {'C': 10}
Trained clf with 0.219 zeros in 2.150 s
Best params: {'C': 10}
Trained clf with 0.422 zeros in 1.411 s
Best params: {'C': 10}
Trained clf with 0.562 zeros in 1.823 s
Best params: {'C': 10}
Trained clf with 0.391 zeros in 1.252 s
Best params: {'C': 10}
Trained clf with 0.609 zeros in 1.435 s
Best params: {'C': 10}
Trained clf with 0.312 zeros in 2.578 s
Best params: {'C': 10}
Trained clf with 0.297 zeros in 1.343 s
Best params: {'C': 10}
Trained clf with 0.703 zeros in 1.031 s
Best params: {'C': 10}
Joint Gaussian conditioning on observed elements
Trained clf with 0.469 zeros in 1.225 s
Best params: {'C': 10}
Trained clf with 0.484 zeros in 0.997 s
Best params: {'C': 10}
Trained clf with 0.141 zeros in 2.866 s
Best params: {'C': 10}
Trained clf with 0.391 zeros in 1.219 s
Best params: {'C': 10}
Joint Gaussian conditioning on observed elements
Trained clf with 0.250 zeros in 2.449 s
Best params: {'C': 10}
Trained clf with 0.047 zeros in 2.910 s
Best params: {'C': 1}
kNN dot product
dot NN: best K for acc/mse: 15/15
Traceback (most recent call last):
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 709, in <module>
    budget, dataset_name, policy_name, num_blocks)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 465, in test_missing_value_methods_for_budget
    Xm_test, y_pred = knn_impute(Xm_test, mask_test, X, mask, y, 'dot')
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 295, in knn_impute
    nn_ind = _knn(X, mask, Xc, best_k_for_acc, verbose=True)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 238, in _knn_dot
    nn_ind[n, :] = bn.argpartsort(dists, k)[:k]
AttributeError: 'module' object has no attribute 'argpartsort'
Trained clf with 0.281 zeros in 1.846 s
Best params: {'C': 10}
Trained clf with 0.203 zeros in 1.343 s
Best params: {'C': 10}
Trained clf with 0.047 zeros in 1.885 s
Best params: {'C': 1}
kNN dot product
dot NN: best K for acc/mse: 15/15
Traceback (most recent call last):
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 709, in <module>
    budget, dataset_name, policy_name, num_blocks)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 465, in test_missing_value_methods_for_budget
    Xm_test, y_pred = knn_impute(Xm_test, mask_test, X, mask, y, 'dot')
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 295, in knn_impute
    nn_ind = _knn(X, mask, Xc, best_k_for_acc, verbose=True)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 238, in _knn_dot
    nn_ind[n, :] = bn.argpartsort(dists, k)[:k]
AttributeError: 'module' object has no attribute 'argpartsort'
Trained clf with 0.312 zeros in 1.146 s
Best params: {'C': 10}
Trained clf with 0.219 zeros in 1.257 s
Best params: {'C': 10}
Joint Gaussian conditioning on observed elements
Trained clf with 0.047 zeros in 1.619 s
Best params: {'C': 10}
kNN dot product
dot NN: best K for acc/mse: 15/15
Traceback (most recent call last):
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 709, in <module>
    budget, dataset_name, policy_name, num_blocks)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 465, in test_missing_value_methods_for_budget
    Xm_test, y_pred = knn_impute(Xm_test, mask_test, X, mask, y, 'dot')
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 295, in knn_impute
    nn_ind = _knn(X, mask, Xc, best_k_for_acc, verbose=True)
  File "/home/nahmed/dip-cv_projects/anytime_recognition/project_281b.py", line 238, in _knn_dot
    nn_ind[n, :] = bn.argpartsort(dists, k)[:k]
AttributeError: 'module' object has no attribute 'argpartsort'
Index([u'mean: 91.519'], dtype='object')
Index([u'mean, full: 0.476'], dtype='object')
```

**Comment by pauros** [comment]
I am trying to analyse historical labourforce data where in a particular year technology has affected employment either people losing jobs or are hired. I kindly  need  data and a code to plot the graph

Thank you
